# Generated by Django 5.0.4 on 2024-08-08 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 13, 1, 58, 638696, tzinfo=datetime.timezone.utc)),
        ),
    ]
