# Generated by Django 5.1 on 2024-08-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothes',
            new_name='Clothesss',
        ),
    ]
