# Generated by Django 5.1 on 2024-08-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_clothes_clothesss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothesss',
            new_name='Clothes',
        ),
    ]
